kraken:
    secret: "put your kraken secret here"
    key: "put your kraken key here"
poloniex:
    secret: "put your poloniex secret here"
    key: "put your poloniex key here"
bitstamp:
    secret: "put your bitstamp secret here"
    key: "put your bitstamp key here"
    customer_id: "put your bitstamp customer id here"
binance:
    secret: "put your binance secret here"
    key: "put your binance key here"
sheets:
    id: 'your google sheets id'
    secret_file: 'configs/client_secret.json'
bugsnag:
    api_key: 'bugsnag api key here'
    stage: 'development'
server:
    port: 8889